account = "gfi.testnet"
secret = "5znd5chmzLmfWcvxXtRLjLWe17ZN4rwKBDy4gzMCRf6Z4beq2R2f3pKpC52S5Srbbb3MruLYFMpWp4pQFMKtcjND"
rpc = "https://rpc.testnet.near.org"
nargo_workspace_dir = "/home/common/projects/GhostFi"
