[package]
name = "ghostfi"
version = "0.1.0"
authors = ["dndll", "Patrick1904", "calebjacob", "milenakrawczyk"]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
near-sdk = "4.0.0"
near-contract-standards = "4.0.0"