[package]
name = "prover-monolith"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "*"
pretty_env_logger = "*"
eyre = "*"
hex-literal = "*"
hex = "*"
tempfile = "3.8"
config = "0.13"

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_with = { version = "*", features = ["hex"] }
toml = "0.8"

# Http
axum = "0.6.20"
tower-http = { version = "0.4.0", features = ["cors"] }
tokio = { version = "*", features = ["full"] }

# Crypto
blake2 = "0.10"
rand_chacha = "0.3.1"
near-crypto = "0.17.0"
near-account-id = "0.17.0"
bs58 = "0.5.0"
near-fetch = "*"
acvm = { git = "https://github.com/noir-lang/noir.git" }
num-bigint = "0.4.3"
num-traits = "0.2.15"

registrar = { path = "../../crates/registrar" }
mrtd = "0.5.1"